flags:
  citeproc:
    executable: true
    icu: false
resolver: lts-17.5
extra-deps:
  - git: https://github.com/jgm/unicode-collation.git
    commit: 4baea9499598f64ec4383303813044d36618a3ba
ghc-options:
  "$locals": -fhide-source-paths
